---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/version: "2.2.2"
spec:
  ports:
    - port: 3306
      name: mysql
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/version: "2.2.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/instance: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/instance: mysql
    spec:
      containers:
        - name: mysql
          image: blabla1337/mysql
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3306
          env:
          -  name: MYSQL_DEFAULT_USER
             valueFrom:
               configMapKeyRef:
                 name: mysql
                 key: MYSQL_DEFAULT_USER
          -  name: MYSQL_DEFAULT_PASS
             valueFrom:
               configMapKeyRef:
                 name: mysql
                 key: MYSQL_DEFAULT_PASS
          -  name: MYSQL_ROOT_PASSWORD
             valueFrom:
               configMapKeyRef:
                 name: mysql
                 key: MYSQL_ROOT_PASSWORD
          -  name: MYSQL_DATABASE
             valueFrom:
               configMapKeyRef:
                 name: mysql
                 key: MYSQL_DATABASE            
---